r"""The two sixteen-dimensional lattices, and why there are exactly two.

The heterotic string is a closed string whose two moving directions are
*different theories*: right-movers are the ten-dimensional superstring, with
central charge :math:`c_R = 15`, and left-movers are the twenty-six-dimensional
bosonic string, :math:`c_L = 26`.  Ten of the left-moving directions are
spacetime; the remaining

.. math::  26 - 10 = 16

have nowhere to go, and are compactified on a torus whose lattice
:math:`\Gamma_{16}` modular invariance forces to be **even and self-dual**:

* *even* -- every vector has even norm, so the left-moving levels stay
  half-integral in the right way;
* *self-dual* -- the lattice equals its own dual, ``covolume = 1``.

In sixteen dimensions there are exactly two such lattices, and therefore exactly
two heterotic strings:

=====================  ======  =======  ==================
lattice                roots   rank     gauge algebra
=====================  ======  =======  ==================
:math:`\Gamma_8 \oplus \Gamma_8`   480     16       ``e8 + e8``
:math:`\Gamma_{16} = D_{16}^{+}`   480     16       ``so(32)``
=====================  ======  =======  ==================

Both give ``480 + 16 = 496`` gauge bosons.  That number is *not* put in: it
comes out of the lattice, and it is separately what Green-Schwarz anomaly
cancellation demands of a ten-dimensional theory.  Two unrelated consistency
conditions landing on 496 is the reason anyone took the heterotic string
seriously.

**The two are genuinely hard to tell apart by counting.**  Rank 16 with 480
roots is ``e8 + e8`` *or* ``so(32)``, and
:func:`stringsim.compactification.torus.identify_algebra` honestly returns both.
What separates them is geometry: the ``E_8 \oplus E_8`` roots split into two
mutually orthogonal families of 240, while the ``D_{16}^{+}`` roots form one
connected system.  :func:`stringsim.compactification.torus.decompose_roots`
settles it, reusing the machinery built for the torus rather than special-casing
this.

**What is checked here and what is not.**  Evenness, integrality and
unimodularity are verified for both lattices from an explicitly constructed
basis.  That there are *only* two is a theorem of lattice theory (Niemeier's
classification in the adjacent case; in dimension 16 it is due to Witt) and is
not proved here -- what the code shows is that both candidates satisfy every
condition, and that they are inequivalent.
"""

from __future__ import annotations

import itertools
from dataclasses import dataclass

import numpy as np

from ..compactification.torus import decompose_roots, identify_algebra

__all__ = [
    "RootLattice",
    "e8",
    "e8_squared",
    "d16_plus",
    "heterotic_lattices",
    "even_self_dual_dimension_rule",
    "GAUGE_DIMENSION",
]

GAUGE_DIMENSION = 496
"""``dim G`` for either heterotic string: 480 roots plus 16 Cartan generators."""

_TOL = 1e-9


def _integer_row_basis(rows: list[list[int]]) -> list[list[int]]:
    """A basis of the lattice generated by integer row vectors, in echelon form.

    Plain integer Gaussian elimination: within each column, repeatedly reduce
    every row against the one with the smallest non-zero entry until only that
    one survives.  Exact -- Python integers throughout -- and the result is
    upper triangular on its pivot columns, so a square answer has determinant
    equal to the product of its diagonal.
    """
    matrix = [list(map(int, row)) for row in rows]
    if not matrix:
        return []
    n_cols = len(matrix[0])
    pivot = 0
    for col in range(n_cols):
        if pivot >= len(matrix):
            break
        while True:
            nonzero = [i for i in range(pivot, len(matrix)) if matrix[i][col] != 0]
            if not nonzero:
                break
            best = min(nonzero, key=lambda i: abs(matrix[i][col]))
            matrix[pivot], matrix[best] = matrix[best], matrix[pivot]
            remaining = False
            for i in range(pivot + 1, len(matrix)):
                if matrix[i][col]:
                    factor = matrix[i][col] // matrix[pivot][col]
                    matrix[i] = [
                        a - factor * b
                        for a, b in zip(matrix[i], matrix[pivot], strict=True)
                    ]
                    if matrix[i][col]:
                        remaining = True
            if not remaining:
                break
        if matrix[pivot][col] != 0:
            pivot += 1
    return matrix[:pivot]


@dataclass(frozen=True)
class RootLattice:
    """An even self-dual lattice, described by its roots and any extra generators.

    Parameters
    ----------
    name:
        Label, e.g. ``"E8 + E8"``.
    roots:
        All vectors of squared length 2, shape ``(n_roots, dim)``.
    extra:
        Generators the roots alone do not produce.  Empty for ``E_8``, whose
        root lattice is the whole thing; for ``D_{16}^{+}`` it holds the spinor
        class vector ``(1/2, ..., 1/2)``, which has norm 4 and so is not a root
        but is needed to make the lattice self-dual.
    """

    name: str
    roots: np.ndarray
    extra: np.ndarray | None = None

    def __post_init__(self) -> None:
        roots = np.asarray(self.roots, dtype=float)
        if roots.ndim != 2:
            raise ValueError(f"roots must be a 2-D array, got shape {roots.shape}")
        extra = (
            np.zeros((0, roots.shape[1]))
            if self.extra is None
            else np.asarray(self.extra, dtype=float).reshape(-1, roots.shape[1])
        )
        object.__setattr__(self, "roots", roots)
        object.__setattr__(self, "extra", extra)
        # basis() runs an exact integer elimination, which is slow enough to be
        # worth doing once per lattice; the lattice is frozen, so this is safe.
        object.__setattr__(self, "_cache", {})

    # -- shape --------------------------------------------------------------

    @property
    def dim(self) -> int:
        return int(self.roots.shape[1])

    @property
    def n_roots(self) -> int:
        return int(self.roots.shape[0])

    @property
    def generators(self) -> np.ndarray:
        """Roots and extra vectors together."""
        return np.vstack([self.roots, self.extra])

    # -- lattice properties -------------------------------------------------

    def basis(self) -> np.ndarray:
        """A basis, found by integer elimination on twice the generators.

        Coordinates lie in ``(1/2) Z``, so doubling makes everything integral;
        the basis is then halved again on the way out.
        """
        if "basis" not in self._cache:
            doubled = np.rint(2.0 * self.generators).astype(int)
            if not np.allclose(doubled / 2.0, self.generators, atol=_TOL):
                raise ValueError("generators are not half-integral")
            rows = _integer_row_basis(doubled.tolist())
            if len(rows) != self.dim:
                raise ValueError(
                    f"generators span {len(rows)} dimensions, not {self.dim}"
                )  # pragma: no cover
            self._cache["basis"] = np.array(rows, dtype=float) / 2.0
        return self._cache["basis"]

    def gram(self) -> np.ndarray:
        """Gram matrix of :meth:`basis`."""
        if "gram" not in self._cache:
            b = self.basis()
            self._cache["gram"] = b @ b.T
        return self._cache["gram"]

    def covolume(self) -> float:
        """``sqrt(det Gram)``; 1 exactly when the lattice is self-dual."""
        return float(np.sqrt(abs(np.linalg.det(self.gram()))))

    def is_integral(self) -> bool:
        """Every pairwise inner product of basis vectors is an integer."""
        gram = self.gram()
        return bool(np.all(np.abs(gram - np.rint(gram)) < 1e-8))

    def is_even(self) -> bool:
        """Every basis vector has even norm.

        For an integral lattice that is enough: expanding
        ``(sum a_i b_i)^2`` leaves even diagonal terms and twice the integer
        cross terms, so every vector is even.
        """
        diagonal = np.diag(self.gram())
        return self.is_integral() and bool(
            np.all(np.abs(diagonal - 2.0 * np.rint(diagonal / 2.0)) < 1e-8)
        )

    def is_unimodular(self) -> bool:
        """``|det Gram| = 1``, i.e. the lattice equals its dual."""
        return abs(abs(np.linalg.det(self.gram())) - 1.0) < 1e-6

    def is_even_self_dual(self) -> bool:
        """Both conditions modular invariance imposes on the internal lattice."""
        return self.is_even() and self.is_unimodular()

    def roots_have_norm_two(self) -> bool:
        """Sanity: everything called a root really has squared length 2."""
        return bool(np.allclose(np.sum(self.roots * self.roots, axis=1), 2.0))

    # -- the gauge algebra --------------------------------------------------

    @property
    def components(self) -> list[tuple[int, int]]:
        """``[(rank, n_roots), ...]`` for the irreducible pieces of the root system."""
        return decompose_roots(self.roots)

    @property
    def algebra(self) -> str:
        """The gauge algebra, named from the root geometry."""
        from ..compactification.torus import _name_from_roots

        return _name_from_roots(self.roots, self.dim)

    @property
    def algebra_candidates_from_counting(self) -> tuple[str, ...]:
        """What the rank and root count alone allow -- both heterotic algebras."""
        return identify_algebra(self.dim, self.n_roots)

    @property
    def algebra_dimension(self) -> int:
        """``roots + rank``: 496 for both heterotic lattices."""
        return self.n_roots + self.dim

    def __str__(self) -> str:  # pragma: no cover - display only
        return (
            f"{self.name:<10s} dim {self.dim}, {self.n_roots} roots, "
            f"algebra {self.algebra} of dimension {self.algebra_dimension}"
        )


# ---------------------------------------------------------------------------
# the lattices
# ---------------------------------------------------------------------------


def _d_roots(dim: int) -> np.ndarray:
    r"""``+/- e_i +/- e_j`` for ``i < j``: the ``D_n`` roots, ``2n(n-1)`` of them."""
    out = []
    for i, j in itertools.combinations(range(dim), 2):
        for sign_i in (1.0, -1.0):
            for sign_j in (1.0, -1.0):
                vector = np.zeros(dim)
                vector[i] = sign_i
                vector[j] = sign_j
                out.append(vector)
    return np.array(out)


def _spinor_class(dim: int, even_minus_signs: bool = True) -> np.ndarray:
    r"""Vectors ``(+/-1/2, ..., +/-1/2)`` with an even number of minus signs."""
    out = []
    for signs in itertools.product((0.5, -0.5), repeat=dim):
        negatives = sum(1 for s in signs if s < 0)
        if (negatives % 2 == 0) == even_minus_signs:
            out.append(np.array(signs))
    return np.array(out)


def e8() -> RootLattice:
    r"""The :math:`E_8` lattice: 240 roots, even, self-dual, dimension 8.

    Constructed as the union of the :math:`D_8` roots (112 of them) and the
    even half-integer vectors (128), which is the standard description
    :math:`E_8 = D_8 \cup (D_8 + s)` restricted to norm 2.  Its root lattice is
    the whole lattice, so no extra generator is needed.
    """
    roots = np.vstack([_d_roots(8), _spinor_class(8)])
    return RootLattice("E8", roots)


def e8_squared() -> RootLattice:
    r""":math:`E_8 \oplus E_8`: two orthogonal copies, 480 roots in 16 dimensions."""
    single = e8().roots
    zeros = np.zeros((len(single), 8))
    roots = np.vstack(
        [np.hstack([single, zeros]), np.hstack([zeros, single])]
    )
    return RootLattice("E8 + E8", roots)


def d16_plus() -> RootLattice:
    r""":math:`D_{16}^{+}`: the ``D_16`` root lattice plus one spinor class.

    The 480 roots are the ``D_16`` ones; the spinor vectors
    :math:`(\pm\tfrac12)^{16}` have norm 4, so they are *not* roots, but one of
    them must be included as a generator or the lattice is not self-dual --
    ``D_16`` alone has covolume 2.  That extra coset is what turns ``so(32)``'s
    root lattice into an even self-dual one, and it is why the gauge group is
    ``Spin(32)/Z_2`` rather than ``SO(32)``.
    """
    roots = _d_roots(16)
    spinor = np.full((1, 16), 0.5)
    return RootLattice("D16+", roots, spinor)


def heterotic_lattices() -> dict[str, RootLattice]:
    """The two even self-dual sixteen-dimensional lattices, by name."""
    return {"E8 + E8": e8_squared(), "Spin(32)/Z2": d16_plus()}


def even_self_dual_dimension_rule(dim: int) -> bool:
    r"""Whether a positive-definite even self-dual lattice can exist in ``dim``.

    They exist only when ``dim`` is a multiple of 8 -- a theorem, stated here
    rather than proved.  It is the reason 16 works: the heterotic string needs
    exactly ``26 - 10 = 16`` internal left-moving directions, and 16 happens to
    be a permitted dimension.  Had the two critical dimensions differed by
    anything else, there would be no heterotic string.
    """
    if dim < 0:
        raise ValueError("dimension must be non-negative")
    return dim % 8 == 0
